# -*- coding: utf-8 -*-
"""breast_cancer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cVI4owNA5B5cKm6ljaRZDe31dxZnBTl4
"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score,recall_score,precision_score

bc = load_breast_cancer()

"""### **Preprocessing**"""

x_train, x_test, y_train, y_test = train_test_split(bc.data ,bc.target , test_size= 0.2 , random_state=42)

scaler = MinMaxScaler(feature_range=(0,1))
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

ann = MLPClassifier(hidden_layer_sizes=100)
ann.fit(x_train,y_train)
y_pred_test = ann.predict(x_test)



acc_test = accuracy_score(y_test, y_pred_test)
p = precision_score(y_test, y_pred_test)
r = recall_score(y_test, y_pred_test)

print(f'Accuracy is {acc_test} and Precision is {p} and Recall is {r}')